### ISSUE TITLE
Missing `seed` in config.json

### ISSUE THREAD

**Issue by glicerico** [singnet/simulation#17]
File config.json has no `seed` value, so process crashes when initializing SnetSim instance

**Comment by glicerico** [comment]
Fixed in https://github.com/singnet/simulation/pull/16

**Comment by joecoope** [comment]
Thanks. The cause is good..Sent from my Telstra Essential Pro on the Telstra Mobile NetworkOn 30 Mar. 2020 12:48 am, Andres Suarez <notifications@github.com> wrote:
File config.json has no seed value, so process crashes when initializing SnetSim instance
