### ISSUE TITLE
Missing oneofeach1 directory

### ISSUE THREAD

**Issue by glicerico** [singnet/simulation#25]
The marketplace notebook (https://github.com/singnet/simulation/blob/master/marketplace.ipynb), in line `In[51]` refers to a pre-run folder `oneofeach1`, which is not in the repository.

I have been trying to generate the folder myself by running the simulation, but I get the error reported in issue https://github.com/singnet/simulation/issues/28

**Comment by deborahduong** [comment]
A limit to files over 100M was enforced in github, so i gzipped the file beneath this directory, and gunzipped it in the notebook
